### ISSUE TITLE
Recipe Schema Different from actual data

### ISSUE THREAD

**Issue by MyUsernamee** [PrismarineJS/node-minecraft-data#122]
When you use the mcData.recipes[id] the data returned doesnt match the schema provided on the website.

For instance from what I can tell as of this moment, you cant get furnace recipes using mcdata.

Output from mcdata:
`: Object {inShape: [[14, 14, 14], [null, 613, null], [null, 613, null]], result: Object {count: 1, id: 590}}
1: Object {inShape: [[963, 963, 963], [null, 613, null], [null, 613, null]], result: Object {count: 1, id: 590}}`

Website Schema:
![image](https://user-images.githubusercontent.com/86261814/145151421-bf6a07ef-0bbf-4e59-8c9d-ac5d68232d7a.png)

**Comment by extremeheat** [comment]
The schema there is used on bedrock only currently. See the schema JSON in Minecraft-data for the pc one or see how it's used in prismarine -recipe
