### ISSUE TITLE
Update to use minecraft-data for toMajor()

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/node-minecraft-data#13]
lib/loader.js currently gets the major version from the release version by splitting the string:

```javascript
function toMajor(mcVersion)
{
  var parts=mcVersion.split(".");
  if(parts.size<=1)
    return null;
  mcVersion=parts.slice(0,2).join(".");
  return mcVersion;
}
```

This works for full releases, but snapshot versions can be said to resemble certain "major" versions, which won't be parsed here. Instead this mapping can be looked up using minecraft-data, after:

https://github.com/PrismarineJS/minecraft-data/pull/92 Add protocol version data

   protocolVersions.json array, "majorVersion" key

(may also want to keep toMajor() as a fallback)

**Comment by rom1504** [comment]
well I did half of that but forgot the other half (https://github.com/PrismarineJS/node-minecraft-protocol/pull/330#issuecomment-174656603).
Will finish this later.
