### ISSUE TITLE
`MinecraftData.IndexedData` misses `loginPacket` type while the value is there?

### ISSUE THREAD

**Issue by WildlandHerald** [PrismarineJS/node-minecraft-data#166]
this code:
```ts
import getData from 'minecraft-data'

const data = getData('1.18.2')
console.log(data.loginPacket)
```
returns
```js
{
  entityId: 227,
  isHardcore: false,
  gameMode: 0,
  previousGameMode: -1,
  worldNames: [
    'minecraft:overworld',
    'minecraft:the_nether',
    'minecraft:the_end'
  ],
  dimensionCodec: {
    type: 'compound',
    name: '',
    value: {
      'minecraft:dimension_type': [Object],
      'minecraft:worldgen/biome': [Object]
    }
  },
  dimension: {
    type: 'compound',
    name: '',
    value: {
      piglin_safe: [Object],
      natural: [Object],
      ambient_light: [Object],
      infiniburn: [Object],
      respawn_anchor_works: [Object],
      has_skylight: [Object],
      bed_works: [Object],
      effects: [Object],
      has_raids: [Object],
      logical_height: [Object],
      coordinate_scale: [Object],
      min_y: [Object],
      has_ceiling: [Object],
      ultrawarm: [Object],
      height: [Object]
    }
  },
  worldName: 'minecraft:overworld',
  hashedSeed: [ -480297713, -2128446749 ],
  maxPlayers: 20,
  viewDistance: 10,
  simulationDistance: 10,
  reducedDebugInfo: false,
  enableRespawnScreen: true,
  isDebug: false,
  isFlat: false
}
```
Yet typings miss the `loginPacket` and I get an error `Property 'loginPacket' does not exist on type 'IndexedData'.` trying to access it.

**Comment by rom1504** [comment]
try not using typescript

otherwise you can add loginPacket in typings

**Comment by WildlandHerald** [comment]
> try not using typescript
> 
> otherwise you can add loginPacket in typings

Not using typescript is fairly inappropriate in my case, I feel rather uncomfortable without it.

Should i create pull request for that? Am i right that adding it in [this file](https://github.com/PrismarineJS/node-minecraft-data/blob/master/typings/index-template.d.ts) would solve it? (not sure how exactly your generator works)

**Comment by nickelpro** [comment]
The login packet is an NBT blob, servers may or may not send all of it or may send extra fields. Similarly, NMD/NMP consumers can feel free to create and send whatever fields they please inside a login packet.

There isn't a good answer for providing typings here. The data is truly arbitrary.

**Comment by WildlandHerald** [comment]
> The login packet is an NBT blob, servers may or may not send all of it or may send extra fields. Similarly, NMD/NMP consumers can feel free to create and send whatever fields they please inside a login packet.
> 
> There isn't a good answer for providing typings here. The data is truly arbitrary.

Yet it would be good idea to point out that the data is at least present here. If none of the fields are required, it can be just
```ts
interface LoginPacket {
    [key: string]: any
}
```
Or some common fields can be represented in typings being optional, like
```ts
interface LoginPacket {
    dimensionCodec?: {
        type: string,
        name: string,
        value: {
            [key: string]: Object
        }
    }
}

**Comment by nickelpro** [comment]
What I'm trying to explain is that the type of the login packet is just `NBT`. Come up with a coherent description for [NBT](https://wiki.vg/NBT) in typescript, then apply it to the login packet. Providing a random spattering of types is inaccurate and misleading. That they happen to appear in the vanilla server for a specific version means nothing, we see plenty of variation among the modded servers.

If someone wanted to create a generator to figure out what the required fields actually are that might be something.

**Comment by extremeheat** [comment]
prismarine nbt exports an NBT type, you can assign that to dimensionCodec or other places of protodef nbt schema

**Comment by nickelpro** [comment]
That seems the right answer to me

**Comment by rom1504** [comment]
@WildlandHerald just do a PR to change https://github.com/PrismarineJS/node-minecraft-data/blob/master/typings/index-template.d.ts#L44
