### ISSUE TITLE
After update to 2.93.1 or above cant use require('minecraft-data')(XX)

### ISSUE THREAD

**Issue by sefirosweb** [PrismarineJS/node-minecraft-data#181]
Hello i'm using minecraft-data library in react application

I'm making a chest inventory viewer but after update the version 2.93.1 or above they stop of working

In the version 2.93.0 works perfect but after update 2.93.1+ seems the requires is changed

I have a simply component to load the minecraft-data

![image](https://user-images.githubusercontent.com/20754836/158056533-c853463a-e424-4f6f-ae3d-10eaacc63166.png)

I'm rewiving the changes https://github.com/PrismarineJS/node-minecraft-data/compare/2.93.0...2.93.1 but I don't see a significant changes

Note: this version works perfect in bot mineflayer based, only is not working from outside packages similar has react / javascript..

**Comment by rom1504** [comment]
Do you have a longer error stack ?

**Comment by sefirosweb** [comment]
Hi Rom, 

Nope the react server don't throw more info:

When I execute a react start server: (npm start)

![image](https://user-images.githubusercontent.com/20754836/158073949-5a67c7ab-6694-41ec-a79c-1f8997558f24.png)

And finally they drop same short error

![image](https://user-images.githubusercontent.com/20754836/158073969-fea67a47-c701-4ea3-9fac-5fbe8eef2360.png)

**Comment by extremeheat** [comment]
There is no bug, you need to update your parser/node to support nodejs 14

**Comment by sefirosweb** [comment]
@extremeheat  what you means of update parser/node?

To execute this code I use a dockerized node "node:16.13-bullseye"

And i don't have this dependency on package.json / .lock

```
{
  "name": "minecraftlegionwebclient",
  "version": "1.2.0",
  "private": false,
  "dependencies": {
    "@testing-library/jest-dom": "5.16.2",
    "@testing-library/react": "12.1.4",
    "@testing-library/user-event": "13.5.0",
    "bootstrap": "4.6.0",
    "express": "4.17.3",
    "install": "0.13.0",
    "js-cookie": "3.0.1",
    "minecraft-assets": "^1.9.0",
    "minecraft-data": "2.93.0",
    "node-fetch": "3.2.3",
    "npm": "8.5.4",
    "react": "17.0.2",
    "react-bootstrap": "1.6.4",
    "react-dom": "17.0.2",
    "react-redux": "7.2.6",
    "react-router": "6.2.2",
    "react-router-dom": "6.2.2",
    "react-scripts": "4.0.3",
    "redux": "4.1.2",
    "redux-thunk": "2.4.1",
    "request": "2.88.2",
    "socket.io-client": "4.4.1",
    "web-vitals": "2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "standard": "npx standard --fix",
    "dockerbuild": "docker build -t minecraftlegionwebclient .",
    "dockerbuildprod": "docker build -t minecraftlegionwebclient -f Dockerfile.prod .",
    "dockerrun": "docker run -d --rm -p:3000:3000 minecraftlegionwebclient",
    "docker": "docker run --rm -it --name minecraftLegionWebClient -v ~/.gitconfig:/etc/gitconfig -p 3000:3000 --network minecraftLegionNetwork  -v $PWD:/home/app -w /home/app -u node node:16.13-bullseye /bin/bash",
    "update": "npx npm-check-updates"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "description": "Front end client for minecraft legion server",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sefirosweb/minecraftLegionWebClient.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/sefirosweb/minecraftLegionWebClient/issues"
  },
  "homepage": "/"
}
```

**Comment by sefirosweb** [comment]
I'm trying to upgrade the react librarys on my project

I have a bit different error but from same source, in this case throw an erro about "fs" and "path" is not installed

But both dependencies are from NODE library correct? don't need to be installed, right?


![image](https://user-images.githubusercontent.com/20754836/158677889-14c9bae6-da77-402f-8ae5-a216cde44890.png)

**Comment by sefirosweb** [comment]
Hi after upgrade react version & minecraft-data seems works correctly

Now the issue comes from minecraft-assets, I saw is not supported for browsers, is oriented into node.js and they can't be loaded in frontend has react / vue..
This happens because fs & path is for backends
More Info: https://github.com/facebook/create-react-app/issues/11756

**Comment by extremeheat** [comment]
If you want to use in a browser you need to have correct webpack settings. Look at prismarine web client for an example configuration
