### ISSUE TITLE
Drops always empty

### ISSUE THREAD

**Issue by Eejit43** [PrismarineJS/node-minecraft-data#194]
The `drops` field of any `Block` always (at least in each test I've run) returns an empty array instead of the actual drops.

Example (stone):

[minecraft-data](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.17/blocks.json#L45):
```
"drops": [
    21
],
```

using `MinecraftData.blocks`:
```
drops: [],
```

Apologies if this is an issue on my end, but from what I can tell, it is an issue with the package.

**Comment by extremeheat** [comment]
Use the loot table data, the drops field in blocks.json is deprecated

**Comment by extremeheat** [comment]
Also where in the documentation did you find that field? Or did you just find it logging the block object?

**Comment by Eejit43** [comment]
I see, thank you! As to where I found it, I have no clue. Likely through logging the block obejct however

**Comment by Eejit43** [comment]
I won't reopen this but quick semi-related question:

using `minecraftData('1.18.2')`, I'm unable to access information for blocks such as `Copper Ore`. Also, `dropChance`s for a lot of items are very incorrect, such as for leaves, unless I'm looking at them incorrectly...

**Comment by extremeheat** [comment]
>  I now realize this is a better question for PrismarineJS/minecraft-data

yes. I believe there is an open PR to fix some pc data.

**Comment by Eejit43** [comment]
> > I now realize this is a better question for PrismarineJS/minecraft-data
> 
> yes. I believe there is an open PR to fix some pc data.

shouldn't this project automatically pull block data from the other versions though? like what I assume https://minecraft-data.prismarine.js.org does. sorry if that is incorrect. I was unable to find a PR that fixed pc block loot data, and it seems like a *lot* of block loot data is inaccurate, but yeah I'll open an issue there
