### ISSUE TITLE
Question: can i use this to ping my mc SUBservers (i have proxy network with TCPShield) 

### ISSUE THREAD

**Issue by TheJoshue** [PrismarineJS/node-minecraft-data#215]
Hello
can i even use this package using nodejs to ping my subservers? not the proxy server, i can already do that
i want to ping subservers which are fully portected by tcpshield, the problem is that no other nodejs package i tried specifically including in their names `minecraft-status`/`minecraft-ping` can NOT do this (probably because of TCPShield?)

can this one do? if so, how can i utilize ping method to ping and get promise (`.then`)?

Thanks in advance!!!

**Comment by rom1504** [comment]
Is there a open rule in your firewall to allow you to access these "sub
servers" on the Minecraft port from your IP?

If yes, then you can do it with node-minecraft-protocol, otherwise no

Node-minecraft-data doesn't do any network at all.
