### ISSUE TITLE
1.13 Release?

### ISSUE THREAD

**Issue by ROMTypo** [PrismarineJS/node-minecraft-data#25]
When is there going to be a 1.13 release for this package

**Comment by lluiscab** [comment]
I'm currently waiting for the maintainers of minecraft-data to merge my PR providing support for 1.13, so I'd hope for this package to be updated as soon as that's done

**Comment by roblabla** [comment]
Depends on: https://github.com/PrismarineJS/minecraft-data/pull/201#issuecomment-411186588

**Comment by rom1504** [comment]
done
