### ISSUE TITLE
Error with tsconfig.json in VScode

### ISSUE THREAD

**Issue by rqbik** [PrismarineJS/node-minecraft-data#28]
![image](https://user-images.githubusercontent.com/47535238/64479025-a5a94680-d1b9-11e9-983e-0905153ca30d.png)

**Comment by rom1504** [comment]
what did you run

**Comment by rqbik** [comment]
Well, I didn't run anything. It's just a problem with vscode I guess, because this error only shows up when im looking at the 'minecraft-data' folder in 'node_modules'. It doesn't do anything and I can just restart vscode to remove this error. It's just annoying.

**Comment by rqbik** [comment]
I guess simply removing the "tests/minecraft-data.ts" line in tsconfig.json should fix the problem? 
Seems like VScode is trying to locate the 'minecraft-data.ts' file in 'tests' folder. 
When VScode sees that this file is unavailable it displays an error.

![image](https://user-images.githubusercontent.com/47535238/64491917-5d039300-d276-11e9-8292-3c91cc4e18d2.png)
