### ISSUE TITLE
Would adding more specific data be a valid pull request?

### ISSUE THREAD

**Issue by Darker** [PrismarineJS/node-minecraft-data#3]
I was considering adding information such as item durability, block transparency, blast resistance...

So far I'm basically making pararell database where I keep any missing info I need as well as more API. But maybe merging the work would be more efficient.

**Comment by rom1504** [comment]
Yeah definitely adding more data would make sense.
Better to open an issue in minecraft-data instead though.

How are you getting that information ? manually ? (currently most of the info in minecraft-data is automatically extracted from the wiki, maybe the info you want to add is on the wiki too)

**Comment by rom1504** [comment]
* durability is available in the wiki (see http://minecraft.gamepedia.com/Shovel)
* transparency too (http://minecraft.gamepedia.com/Glass)
* and blast resistance too

I believe it wouldn't be too hard to add these to the extractor scripts (https://github.com/PrismarineJS/minecraft-data/blob/master/bin/wiki_extractor/block_extractor.js and https://github.com/PrismarineJS/minecraft-data/blob/master/bin/wiki_extractor/item_extractor.js)

If you have more ideas into data that would be useful please share ;)

I think it is better to have extractor script to generate the data automatically than writing the data manually.

**Comment by rom1504** [comment]
Now tracked in https://github.com/PrismarineJS/minecraft-data/issues/83
